[package]
name = "rocket-pastebin"
version = "0.1.0"
authors = ["Damien Castelltort <dcastelltort@gmail.com>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rand = "0.3"
crossbeam = "0.3.2"