[global]
limits = { forms = 32768 }

[development]
address = "localhost"
port = 8000
workers = 2
log = "normal"
secret_key = "kkQt70sTLNHtYP8wEgocLTaWWaV16HgT92zOy1/4g68="


[staging]
address = "0.0.0.0"
port = 8080
workers = 4
log = "normal"
secret_key = "Qk2SYrVNt4LJLM6MEoKMS3ZJlT/ZSIVtq/wV/511vn0="

[production]
address = "0.0.0.0"
port = 80
workers = 8
log = "critical"
secret_key = "sADsjhP4BKvuDTOlJL8OI/hBI+jRjM652Vn4iI7lHKg="